### ISSUE TITLE
Exit code is 0 even if auth failed

### ISSUE THREAD

**Issue by Taknok** [infothrill/python-dyndnsc#197]
## Description
When using a wrong password (or even a wrong user) the process exit with a code 0 letting think that everything ran smoothly. Which is not the case.

`dyndnsc 0.6.1`

## Example to reproduce:
The `demo.conf` file
```toml
[dyndnsc]
configs = myconf_ipv4, myconf_ipv6

[myconf_ipv4]
# this will update your ipv4 address to the address
# the detector dnswanip returns:
use_preset = nsupdate.info:ipv4
updater-hostname = test-demo.nsupdate.info
updater-userid = test-demo.nsupdate.info
updater-password = NotAValidPassword
detector = webcheck4

[myconf_ipv6]
# this will update your ipv6 address to the address
# the detector dnswanip returns:
use_preset = nsupdate.info:ipv6
updater-hostname = test-demo.nsupdate.info
updater-userid = test-demo.nsupdate.info
updater-password = NotAValidPassword
detector = webcheck6
```

The commands:
```bash
dyndnsc -vvv -c ./demo.conf
echo $?
```
